# Generated by Django 5.1.1 on 2024-10-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
