# Generated by Django 5.1.1 on 2024-10-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_flight_latitude_flight_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='query',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteapp.flight'),
        ),
    ]
