# Generated by Django 5.1.1 on 2024-10-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_remove_searchhistory_query_searchhistory_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='search_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
